# Generated by Django 5.1.6 on 2025-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mail',
            field=models.EmailField(default='anonymous', max_length=254),
        ),
    ]
